# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9aceb7fa75adab097ea70a7286c538494fa3101c9dac35e0bdd2612da619a675941029e65399dd917f075f0dee6f37c3dad3d32d7dc2386be8bbd2b25789eb5

test:
  secret_key_base: 9bd232126491f403b2a9c4aec42d3a3acdabd5f1bb91d92f756a1482662af9e31a4f2f76f22d76f7ce58442c9db43ed74bf2dc4594a1a1221ac79a8a6970e041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
