# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9400e6196594b9ab3f4b8e8ee04208648b7b170963dbf1f1a0c4d4940b903c6ab4d219112a8e06707184419c44a3bd857e78ffad399fc67e03ade3331671776b

test:
  secret_key_base: 6a35432a2f498dc0abcfde84f34046c2ffe43ff30a6f5cb1dc429587f5485383867a9fdb788a8bd7eeb572e3cd2ba37033c7c12bd5a0643bb7b33ca93c3e78f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
